Loading, Displaying, Resizing, and Writing Images with Python

In [3]:
import cv2
img=cv2.imread('galaxy.jpg',1)#colour 1, b/w 0, -1 transparency capabilities

print(type(img))#datetype
print(img)#array
print(img.shape)#shape
print(img.ndim)#dimensions
#resize image
resized_image=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))#resize
cv2.imshow("Galaxy",resized_image) #show window
cv2.imwrite('Galaxy_resized.jpg',resized_image)
cv2.waitKey(2000)#t ime to close window in miliseconds
cv2.destroyAllWindows()#closes windows


<class 'numpy.ndarray'>
[[[19 15 10]
  [23 19 14]
  [21 15 10]
  ...
  [27 22 13]
  [20 18  8]
  [21 19  9]]

 [[17 13  8]
  [21 18 10]
  [19 13  6]
  ...
  [27 22 13]
  [22 17  8]
  [24 19 10]]

 [[17 14  6]
  [18 15  7]
  [21 18 10]
  ...
  [23 16  7]
  [33 26 17]
  [30 23 14]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 5  5  5]
  [ 8  8  8]
  [14 14 14]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 2  2  2]
  [ 3  3  3]
  [ 9  9  9]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 3  3  3]]]
(1485, 990, 3)
3


Exercise: Batch Image Resizing

In [4]:
import glob

images=glob.glob("*.jpg")

for image in images:
    img=cv2.imread(image,0)
    re=cv2.resize(img,(100,100))
    cv2.imshow("Batch Image Resizing",re)
    cv2.waitKey(500)
    cv2.destroyAllWindows()
    cv2.imwrite("resized_"+image,re)

Face Detection

In [15]:
face_cascade=cv2.CascadeClassifier('./haarcascade_frontalface_default.xml')
img2=cv2.imread('news.jpg')
gray_img=cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)

#Search for face and will return coordiantes of face. comes out as numpy array
faces=face_cascade.detectMultiScale(gray_img,
                                   scaleFactor=1.1,
                                   minNeighbors=5)
for x, y, w, h in face:
    img2=rectangle(img, (x,y),(x+w,y+h),(0,255,0),3)#top left corner then bottom right corner

resized=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow('Gray',img2)
cv2.waitKey(2000)
cv2.destroyAllWindows()


error: /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:11111: error: (-215) scn == 3 || scn == 4 in function cvtColor


Capturing Video from Webcam

In [21]:
import time #let video run longer
video=cv2.VideoCapture(0)
a=0
while True:
    a=a+1
    check, frame =video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)


    #time.sleep(5)
    cv2.imshow('Capturing',gray)
    key=cv2.waitKey(2000)
    if key==ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()