Intro to Numpy

In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [2]:
import numpy as np
n=np.arange(27)
print (n) #Numpy Array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [3]:
#two dimensional array
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
#three dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
#as array
m=np.asarray([[123,12,123,12,33],[],[]])
m

array([[123, 12, 123, 12, 33], [], []], dtype=object)

In [6]:
import cv2 

ModuleNotFoundError: No module named 'cv2'